### ISSUE TITLE
"open trading" examples

### ISSUE THREAD

**Issue by tsarbuig** [tsarbuig/LimitSwap#1]
https://bscscan.com/tx/0xb42089396c1b1f887cb79e0cf48ae785aa92fa66f0645c759244f70b2a2834f9

**Comment by tsarbuig** [comment]
https://bscscan.com/tx/0x19cac49bf8319689a7620935bf9466e469317992b994ec9692697a9ef71e3ace

**Comment by tsarbuig** [comment]
https://t.me/LimitSwap/98953

https://github.com/prt1999/sample_event

**Comment by c133** [comment]
UNISWAP (ETH):

https://etherscan.io/tx/0x303143b2015a398050a50e4dc2ef16668b974c06db2fd4c4e4abbe64f0c2d592

Function: enableTrading()

MethodID: 0x8a8c523c

**Comment by tsarbuig** [comment]
# https://bscscan.com/tx/0xa98ae84de5aee32d216d734b790131a845548c7e5013085688dccd58c9b5b277
    # Function: tradingStatus
    # MethodID: 0x0d295980

    # https://bscscan.com/tx/0x0c528819b84a7336c3ff1cc72290ba8ca48555b932383fcbe6722a703a6b72a4
    # Function: SetupEnableTrading
    # MethodID: 0x7b9e987a

**Comment by mjsal** [comment]
https://bscscan.com/tx/0xb31665e58e83fe3b3ac63746f0a1c8aeffcaab9b8881a370b689891be21eefd4

Function: setTradingIsEnabled

MethodID: 0xe27ad5eb
