### ISSUE TITLE
TRAILING STOP Bug

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#100]
Hello
"SELECT_MODE": "trailing_stop"

First, I set the price of the sale of the token:

08-15 06:36:34.202772 TRAILING STOP PEEL | Token price 0.1517847419 BUSD | ATH 0.1517847419 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:37:01.204399 TRAILING STOP PEEL | Token price 0.1517723629 BUSD | ATH 0.1517847419 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:37:34.092683 TRAILING STOP PEEL | Token price 0.1517520211 BUSD | ATH 0.1517847419 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:39:25.715067 TRAILING STOP PEEL | Token price 0.1517665633 BUSD | ATH 0.1517847419 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:39:31.502226 TRAILING STOP PEEL | Token price 0.1515616002 BUSD | ATH 0.1517847419 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:39:45.949657 TRAILING STOP PEEL | Token price 0.1517364241 BUSD | ATH 0.1517847419 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:44:43.742702 TRAILING STOP PEEL | Token price 0.1524919801 BUSD | ATH 0.1524919801 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:45:01.102220 TRAILING STOP PEEL | Token price 0.1524853025 BUSD | ATH 0.1524919801 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:46:10.479586 TRAILING STOP PEEL | Token price 0.1524853025 BUSD | ATH 0.1524919801 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:47:27.949444 TRAILING STOP PEEL | Token price 0.1524271402 BUSD | ATH 0.1524919801 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:47:52.222192 TRAILING STOP PEEL | Token price 0.1523102563 BUSD | ATH 0.1524919801 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:50:01.839357 TRAILING STOP PEEL | Token price 0.1522829212 BUSD | ATH 0.1524919801 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 06:51:33.811364 TRAILING STOP PEEL | Token price 0.1522488502 BUSD | ATH 0.1524919801 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000

ATH grows up to: 0.1559616394

08-15 11:55:19.561479 TRAILING STOP PEEL | Token price 0.1422418306 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 11:55:41.565071 TRAILING STOP PEEL | Token price 0.1422757495 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 11:56:31.921327 TRAILING STOP PEEL | Token price 0.1422854840 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 11:57:22.846523 TRAILING STOP PEEL | Token price 0.1422854840 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 11:57:58.382773 TRAILING STOP PEEL | Token price 0.1423407024 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 11:58:19.811830 TRAILING STOP PEEL | Token price 0.1423489861 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 11:58:28.490607 TRAILING STOP PEEL | Token price 0.1428337245 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000
08-15 11:59:13.666556 TRAILING STOP PEEL | Token price 0.1427527448 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1950000000

I change the selling price:

08-17 08:01:41.410455 Loading tokens from ./tokens.json
08-17 08:01:41.582329 BNB  price: 320.87 $
08-17 08:01:41.582329 New TRAILING_STOP_LOSS : 1.0%
08-17 08:01:41.582329 New SELLPRICEINBASE    : 0.153
08-17 08:01:41.582329 New SLIPPAGE           : 1
08-17 08:01:41.582329 New STOPLOSSPRICEINBASE: 0
08-17 08:02:10.271018 TRAILING STOP PEEL | Token price 0.1370642123 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1530000000
08-17 08:02:19.371391 TRAILING STOP PEEL | Token price 0.1373596279 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1530000000
08-17 08:03:36.824513 TRAILING STOP PEEL | Token price 0.1373869917 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1530000000
08-17 08:03:52.419458 TRAILING STOP PEEL | Token price 0.1374593805 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1530000000
08-17 08:05:58.180720 TRAILING STOP PEEL | Token price 0.1374227412 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1530000000

Then the price rises and reaches my sell price, but TRAILING STOP mode does not work (selling immediately):

08-18 07:20:00.989820 TRAILING STOP PEEL | Token price 0.1528219823 BUSD | ATH 0.1559616394 | STOPLOSS 0.0000000000 | 1st Target Price = SELLPRICEINBASE = 0.1530000000
08-18 07:20:25.489820 READY TO SELL PEEL | Token price 0.1533661976 BUSD | ATH 0.1559616394 | 2nd Target Price = ATH - 1.0% = 0.1544020230

08-18 07:20:25.489820 TRAILING STOP target reached : LET'S SELL @ 0.153366197579106883219779

The problem is that ATH cannot be greater than SELLPRICEINBASE in TRAILING STOP mode, but only in READY TO SELL mode
When I decrease the token sale price, the script rereads the file tokens.json, the script should check the ATH value, if it is higher than the token sale price, then do ATH=SELLPRICEINBASE

**Comment by tsarbuig** [comment]
I should do ATH=SELLPRICEINBASE only in TRAILING STOP mode , not during READY TO SELL mode, right ?

I added this code in v5.0.4.4 :
![image](https://user-images.githubusercontent.com/70858574/186275635-ee7c3764-4b8e-407a-8e23-3b8dba7d9719.png)
