### ISSUE TITLE
Set max price on buy the dip 

### ISSUE THREAD

**Issue by chrisonline909** [tsarbuig/LimitSwap#103]
If possible it would be nice to set a max price on buy the dip.  Example. Token is $1usd and would like to buy around 50c at most  using buy the dip 60‰---20%. Price goes to 2 usd then falls to 1usd and raises 20% bot buys. Higher then the around 50c range we initially wanted.

**Comment by tsarbuig** [comment]
done in v5.0.4.4

**Comment by tsarbuig** [comment]
see https://github.com/tsarbuig/LimitSwap/issues/96
