### ISSUE TITLE
Ability to turn off repeat liquidity checks

### ISSUE THREAD

**Issue by wibuf** [tsarbuig/LimitSwap#104]
Basically found a new token from Telegram but under my setting of minimum_liquidity_in_dollars, I would like that check to only happen once then move on to waiting for a new token

**Comment by tsarbuig** [comment]
will be solved with new "wait_for_liquidity" option for AUTOMATICALLY_CHOOSE_LIQUIDITY_PAIR in v5.0.4.4

AUTOMATICALLY_CHOOSE_LIQUIDITY_PAIR = true --> checks only once
AUTOMATICALLY_CHOOSE_LIQUIDITY_PAIR = wait_for_liquidity --> checks repeatedly
