### ISSUE TITLE
Have valuation on screen as bot is running

### ISSUE THREAD

**Issue by just789rice** [tsarbuig/LimitSwap#15]
Is it possible to have the valuation of the token bought on the screen as the bot is running? For example, if I bought $80 worth, it would be great to show "value=$120.  It's a way to keep track of the net gain or loss so one can sell quickly.

**Comment by tsarbuig** [comment]
done https://github.com/tsarbuig/LimitSwap/commit/9b1d0b58219650ca0cf6df023e94511afe50647a
