### ISSUE TITLE
cant buy

### ISSUE THREAD

**Issue by wilsntn** [tsarbuig/LimitSwap#19]
i cant buy tokens 

INFO: 2022-01-16 22:13:58,503    BUY TRANSACTION FAILURE !
INFO: 2022-01-16 22:13:58,503 -------------------------------
INFO: 2022-01-16 22:13:58,503 Type of failures and possible causes:
INFO: 2022-01-16 22:13:58,504 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 1000000 at least
INFO: 2022-01-16 22:13:58,504 - TRANSFER_FROM_FAILED         --> Your BASE token is not approved for trade
INFO: 2022-01-16 22:13:58,504 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
INFO: 2022-01-16 22:13:58,505 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
INFO: 2022-01-16 22:13:58,505 - TRANSFER_FAILED              --> There is a whitelist
INFO: 2022-01-16 22:13:58,505 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds on your wallet to cover fees
INFO: 2022-01-16 22:13:58,505 - ... or your node is not working well

"SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "false",
    "GAS": "boost",
    "BOOSTPERCENT": "30",
    "GASLIMIT": "1000000",
    "GASPRIORITY_FOR_ETH_ONLY": "1.5"

"SYMBOL": "bcoin",
    "ADDRESS": "0x00e1656e45f18ec6747f5a8496fd39b50b38396d",
    "KIND_OF_SWAP": "base",
    "BUYAMOUNTINBASE": "0.05",
    "BUYAMOUNTINTOKEN": "1",
   
    "BUYPRICEINBASE":  "0.007",
    "SELLPRICEINBASE": "200%",
    "STOPLOSSPRICEINBASE": "60%",
    "SLIPPAGE": "5",

can you help me?

**Comment by tsarbuig** [comment]
do you have a Tx in your wallet ?
