### ISSUE TITLE
Couldn't sell

### ISSUE THREAD

**Issue by forp3tessake** [tsarbuig/LimitSwap#27]
I bought a token in presale. When I tried to sell shortly after launch I got this error message:

INFO: 2022-01-21 18:01:13,896 Your wallet already owns :  390155603.30727994 MetaApes
INFO: 2022-01-21 18:01:13,897 You have reached MAXTOKENS for token  MetaApes --> bot stops to buy
INFO: 2022-01-21 18:01:14,067 Current Wallet Balance is : 6.075088569824165648 BNB 
INFO: 2022-01-21 18:01:14,514 Sell Signal Found @0.000000006782259616
INFO: 2022-01-21 18:01:14,517 
INFO: 2022-01-21 18:01:14,517 Sell price in MetaApes/BNB  : 0.000000006782259616
INFO: 2022-01-21 18:01:14,664 Current Wallet Balance is:  390155603.30727994 MetaApes
ERROR: 2022-01-21 18:01:14,664 '>' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "LimitSwap.py", line 5126, in run
  File "LimitSwap.py", line 4079, in sell
TypeError: '>' not supported between instances of 'int' and 'str'

This is my setup:

[
  {
    "ENABLED": "true",

    "SYMBOL": "MetaApes",
    "ADDRESS": "0xd764457Fadd15B52089BeE2b3c38964C7dFf0B70",
    "KIND_OF_SWAP": "base", // enter "base" to use BUYAMOUNTINBASE , and "tokens" to use BUYAMOUNTINTOKENS
    "BUYAMOUNTINBASE": "0",
    "BUYAMOUNTINTOKEN": "",
    "MAX_BASE_AMOUNT_PER_EXACT_TOKENS_TRANSACTION": "0", // used with KIND_OF_SWAP = tokens

    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "0", // You can now put amount in % in this field
    "STOPLOSSPRICEINBASE": "0", // You can now put amount in % in this field
    "SLIPPAGE": "49",

    "MOONBAG": "0", // Bot will keep this amount in your wallet after SELL order
    "MAXTOKENS": "1", // Bot will stop if your balance > MAXTOKENS
    "MAX_SUCCESS_TRANSACTIONS_IN_A_ROW": "3",
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "3",

    "RUGDOC_CHECK": "false",
    "BUYAFTER_XXX_SECONDS": "0", // if you want the bot to wait XXX seconds before if makes the BUY Tx
    "WAIT_FOR_OPEN_TRADE": "false", // check Wiki, this is very useful
    "MULTIPLEBUYS": "false", // use this if you want bot to make multiple buys at the same time
    "BUYCOUNT": "",
    "ALWAYS_CHECK_BALANCE": "true", // use this if you want bot to check your token balance between each price check

    "MINIMUM_LIQUIDITY_IN_DOLLARS": "10000",
    "WATCH_STABLES_PAIRS": "false", // use this if you want bot to check all Stable Liquidity pairs

    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "",
    "BASEADDRESS": "",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "true",
    "GAS": "50", // Team recommend you to use BOOST here
    "MAX_GAS": "", // Put here the maximum of GAS you want to pay if you use BOOST. If GAS > MAX_GAS Tx won't be made
    "BOOSTPERCENT": "30",
    "GASLIMIT": "2000000", // Team recommend you to use 1000000 here
    "GASPRIORITY_FOR_ETH_ONLY": "1.5"
  }
]

**Comment by tsarbuig** [comment]
do not put empty fields, like "MAX_GAS": ""

it's the problem

put MAX_GAS = 99999
