### ISSUE TITLE
limitswap exitted with "please send me this message: '' "

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/LimitSwap#28]
Scanning Mempool & Waiting for New Liquidity Add Event..... Current Block:  ...
Bot will wait 3  seconds before buy, as you entered in BUYAFTER_XXX_SECONDS parameter
Uh oh, please send me this message: ''

My tokens config file has: "BUYAFTER_XXX_SECONDS": "3".

Token is: BSC 0x469aCf8e1F29C1B5Db99394582464Fad45A1fC6F

**Comment by tsarbuig** [comment]
please try again with new Sniper :)

**Comment by tsarbuig** [comment]
please try again with new Sniper :)
