### ISSUE TITLE
Bot sold only 1 of 2 wallets

### ISSUE THREAD

**Issue by forp3tessake** [tsarbuig/LimitSwap#29]
I set up the bot to sell my tokens immediately at launch, with 2 wallets. The first wallet sold, but the second one didn't.

This is the log:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-01-24 19:02:39,572 Current Wallet Balance is : (censored) BNB 
ERROR: 2022-01-24 19:02:40,208 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-01-24 19:02:40,669 Current Wallet Balance is : (censored) BNB 
INFO: 2022-01-24 19:02:41,238 Sell Signal Found @0.000000620033549369
INFO: 2022-01-24 19:02:41,240 
INFO: 2022-01-24 19:02:41,240 Sell price in ONI/BNB  : 0.000000620033549369
INFO: 2022-01-24 19:02:41,365 Current Wallet Balance is:  3500000.0 ONI
INFO: 2022-01-24 19:02:41,869 sell condition 3
INFO: 2022-01-24 19:02:42,261 Transaction Hash =  (censored)
INFO: 2022-01-24 19:02:47,916 ----------------------------------
INFO: 2022-01-24 19:02:47,916 SUCCESS : your sell Tx is confirmed    
INFO: 2022-01-24 19:02:48,151 Current Wallet Balance is : (censored) BNB 
INFO: 2022-01-24 19:02:48,296 Current Wallet Balance is:  0.0 ONI
INFO: 2022-01-24 19:02:48,297 ----------------------------------
ERROR: 2022-01-24 19:02:48,297 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-01-24 19:02:48,714 Current Wallet Balance is : (censored) BNB 
ERROR: 2022-01-24 19:02:49,330 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-01-24 19:02:49,634 Current Wallet Balance is : (censored) BNB 
ERROR: 2022-01-24 19:02:50,160 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

This is my tokens set up:

[
  {
    "ENABLED": "true",

    "SYMBOL": "ONI",
    "ADDRESS": "0xBd68b8D34D2Cac8998aB238d014A321c7fac88C5",
    "KIND_OF_SWAP": "base", // enter "base" to use BUYAMOUNTINBASE , and "tokens" to use BUYAMOUNTINTOKENS
    "BUYAMOUNTINBASE": "0",
    "BUYAMOUNTINTOKEN": "",
    "MAX_BASE_AMOUNT_PER_EXACT_TOKENS_TRANSACTION": "0", // used with KIND_OF_SWAP = tokens

    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "0", // You can now put amount in % in this field
    "STOPLOSSPRICEINBASE": "0", // You can now put amount in % in this field
    "SLIPPAGE": "49",

    "MOONBAG": "0", // Bot will keep this amount in your wallet after SELL order
    "MAXTOKENS": "1", // Bot will stop if your balance > MAXTOKENS
    "MAX_SUCCESS_TRANSACTIONS_IN_A_ROW": "3",
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "3",

    "RUGDOC_CHECK": "false",
    "BUYAFTER_XXX_SECONDS": "0", // if you want the bot to wait XXX seconds before if makes the BUY Tx
    "WAIT_FOR_OPEN_TRADE": "false", // check Wiki, this is very useful
    "MULTIPLEBUYS": "true", // use this if you want bot to make multiple buys at the same time
    "BUYCOUNT": "2",
    "ALWAYS_CHECK_BALANCE": "true", // use this if you want bot to check your token balance between each price check

    "MINIMUM_LIQUIDITY_IN_DOLLARS": "10000",
    "WATCH_STABLES_PAIRS": "false", // use this if you want bot to check all Stable Liquidity pairs

    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "",
    "BASEADDRESS": "",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "true",
    "GAS": "50", // Team recommend you to use BOOST here
    "MAX_GAS": "99999", // Put here the maximum of GAS you want to pay if you use BOOST. If GAS > MAX_GAS Tx won't be made
    "BOOSTPERCENT": "30",
    "GASLIMIT": "2000000", // Team recommend you to use 1000000 here
    "GASPRIORITY_FOR_ETH_ONLY": "1.5"
  }
]

**Comment by tsarbuig** [comment]
it's because it's "MULTIPLEBUYS"... it's only for BUY :)

I will implement it on SELL when I have time :)
