### ISSUE TITLE
So much code!

### ISSUE THREAD

**Issue by yaqub0r** [tsarbuig/LimitSwap#3]
Lin 3639 of LimitSwap.py:

You have 40 lines of code, 20 of which are repeating and you only change one thing, weth instead of outToken. You also check for pool and on and else you give the same error message as your exception. That 40 lines of code should be about 10.

**Comment by tsarbuig** [comment]
solved by https://github.com/tsarbuig/LimitSwap/commit/f982f2ac0ce956019acdb48441c4089874e8b575
