### ISSUE TITLE
feature request: colors for sell and buy

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/LimitSwap#34]
I've noticed that I always have to check the current price before I know if the token is selling or buying. It would be easier to see if the link of the token would be red for tokens that we are getting sold and green for tokens that we are trying to get bought (instead of just alternating the 2 colors).

**Comment by tsarbuig** [comment]
but there is no "tokens that we are trying to get bought" and "tokens that we are trying to get sold"

bot always try to buy AND sell

how could I make a difference ?

**Comment by vaidab** [comment]
I see... then it could print the line it buys in green and sells in red... 
Also tabbing / restructuring would make it easier to read. Here's a sample from my tool:

<img width="1029" alt="Screenshot_2022-01-29_at_21_00_47" src="https://user-images.githubusercontent.com/19855026/151674059-4df45b1a-9d6a-4dec-a86c-9b422dc34a5e.png">
.

**Comment by tsarbuig** [comment]
very interesting, I'll think about that

don't you have source code of this tool ? I like the graphics :)

**Comment by vaidab** [comment]
I'll contact you on tg with the code.

**Comment by tsarbuig** [comment]
done : have put the SELL lines in orange :)

![image](https://user-images.githubusercontent.com/70858574/152246308-3accf57a-b7a4-4cbe-ace9-821d825517c4.png)
