### ISSUE TITLE
Inserted max failed tx = 3, bot tried to sell 6 times. I shut it down manually.

### ISSUE THREAD

**Issue by forp3tessake** [tsarbuig/LimitSwap#37]
I bought a token in presale and wanted to sell shortly after launch.

I inserted "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "3", however, the bot kept trying to sell more than 3 times in a row. It made 6 failed sell transactions before I shut it down manually. It would have probably kept going if I didn't shut it down.

log:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-02-01 18:01:21,714 Your wallet already owns :  222222222.0 BFYC
INFO: 2022-02-01 18:01:21,715 You have reached MAXTOKENS for token  BFYC --> bot stops to buy
INFO: 2022-02-01 18:01:22,012 Current Wallet Balance is : 5.005116316416662407 BNB 
INFO: 2022-02-01 18:01:22,484 Sell Signal Found @0.000000013639299041
INFO: 2022-02-01 18:01:22,487 
INFO: 2022-02-01 18:01:22,487 Sell price in BFYC/BNB  : 0.000000013639299041
INFO: 2022-02-01 18:01:22,567 Current Wallet Balance is:  222222222.0 BFYC
INFO: 2022-02-01 18:01:22,867 sell condition 3
INFO: 2022-02-01 18:01:23,332 Transaction Hash =  *censored*
INFO: 2022-02-01 18:01:29,643 --------------------------------
INFO: 2022-02-01 18:01:29,643    SELL TRANSACTION FAILURE !
INFO: 2022-02-01 18:01:29,644 --------------------------------
INFO: 2022-02-01 18:01:29,644 Type of failures and possible causes:
INFO: 2022-02-01 18:01:29,644 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 1000000 at least
INFO: 2022-02-01 18:01:29,645 - TRANSFER_FROM_FAILED         --> Token is not approved for trade. LimitSwap will check approval right now.
INFO: 2022-02-01 18:01:29,645 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
INFO: 2022-02-01 18:01:29,645 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
INFO: 2022-02-01 18:01:29,645 - TRANSFER_FAILED              --> There is a whitelist
INFO: 2022-02-01 18:01:29,645 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds on your wallet to cover fees
INFO: 2022-02-01 18:01:29,645 - ... or your node is not working well
INFO: 2022-02-01 18:01:29,646 -------------------------------
ERROR: 2022-02-01 18:01:29,764 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-02-01 18:01:29,884 Your wallet already owns :  222222222.0 BFYC
INFO: 2022-02-01 18:01:29,884 You have reached MAXTOKENS for token  BFYC --> bot stops to buy
INFO: 2022-02-01 18:01:30,050 Current Wallet Balance is : 4.905116416416662407 BNB 
INFO: 2022-02-01 18:01:30,366 Sell Signal Found @0.000000019457335698
INFO: 2022-02-01 18:01:30,368 
INFO: 2022-02-01 18:01:30,369 Sell price in BFYC/BNB  : 0.000000019457335698
INFO: 2022-02-01 18:01:30,470 Current Wallet Balance is:  222222222.0 BFYC
INFO: 2022-02-01 18:01:30,694 sell condition 3
INFO: 2022-02-01 18:01:31,066 Transaction Hash =  *censored*
INFO: 2022-02-01 18:01:36,459 --------------------------------
INFO: 2022-02-01 18:01:36,461    SELL TRANSACTION FAILURE !
INFO: 2022-02-01 18:01:36,462 --------------------------------
INFO: 2022-02-01 18:01:36,463 Type of failures and possible causes:
INFO: 2022-02-01 18:01:36,464 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 1000000 at least
INFO: 2022-02-01 18:01:36,465 - TRANSFER_FROM_FAILED         --> Token is not approved for trade. LimitSwap will check approval right now.
INFO: 2022-02-01 18:01:36,466 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
INFO: 2022-02-01 18:01:36,468 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
INFO: 2022-02-01 18:01:36,469 - TRANSFER_FAILED              --> There is a whitelist
INFO: 2022-02-01 18:01:36,471 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds on your wallet to cover fees
INFO: 2022-02-01 18:01:36,471 - ... or your node is not working well
INFO: 2022-02-01 18:01:36,472 -------------------------------
ERROR: 2022-02-01 18:01:36,569 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-02-01 18:01:36,766 Your wallet already owns :  222222222.0 BFYC
INFO: 2022-02-01 18:01:36,767 You have reached MAXTOKENS for token  BFYC --> bot stops to buy
INFO: 2022-02-01 18:01:37,167 Current Wallet Balance is : 4.805116516416662407 BNB 
INFO: 2022-02-01 18:01:37,577 Sell Signal Found @0.000000018508578796
INFO: 2022-02-01 18:01:37,581 
INFO: 2022-02-01 18:01:37,588 Sell price in BFYC/BNB  : 0.000000018508578796
INFO: 2022-02-01 18:01:37,723 Current Wallet Balance is:  222222222.0 BFYC
INFO: 2022-02-01 18:01:38,063 sell condition 3
INFO: 2022-02-01 18:01:38,507 Transaction Hash =  *censored*
INFO: 2022-02-01 18:01:44,661 --------------------------------
INFO: 2022-02-01 18:01:44,661    SELL TRANSACTION FAILURE !
INFO: 2022-02-01 18:01:44,662 --------------------------------
INFO: 2022-02-01 18:01:44,663 Type of failures and possible causes:
INFO: 2022-02-01 18:01:44,663 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 1000000 at least
INFO: 2022-02-01 18:01:44,664 - TRANSFER_FROM_FAILED         --> Token is not approved for trade. LimitSwap will check approval right now.
INFO: 2022-02-01 18:01:44,664 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
INFO: 2022-02-01 18:01:44,664 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
INFO: 2022-02-01 18:01:44,665 - TRANSFER_FAILED              --> There is a whitelist
INFO: 2022-02-01 18:01:44,665 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds on your wallet to cover fees
INFO: 2022-02-01 18:01:44,665 - ... or your node is not working well
INFO: 2022-02-01 18:01:44,665 -------------------------------
ERROR: 2022-02-01 18:01:44,849 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-02-01 18:01:44,973 Your wallet already owns :  222222222.0 BFYC
INFO: 2022-02-01 18:01:44,976 You have reached MAXTOKENS for token  BFYC --> bot stops to buy
INFO: 2022-02-01 18:01:45,152 Current Wallet Balance is : 4.705116616416662407 BNB 
INFO: 2022-02-01 18:01:45,468 Sell Signal Found @0.000000015863136909
INFO: 2022-02-01 18:01:45,469 
INFO: 2022-02-01 18:01:45,469 Sell price in BFYC/BNB  : 0.000000015863136909
INFO: 2022-02-01 18:01:45,703 Current Wallet Balance is:  222222222.0 BFYC
INFO: 2022-02-01 18:01:45,924 sell condition 3
INFO: 2022-02-01 18:01:46,360 Transaction Hash =  *censored*
INFO: 2022-02-01 18:01:54,050 --------------------------------
INFO: 2022-02-01 18:01:54,051    SELL TRANSACTION FAILURE !
INFO: 2022-02-01 18:01:54,052 --------------------------------
INFO: 2022-02-01 18:01:54,053 Type of failures and possible causes:
INFO: 2022-02-01 18:01:54,053 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 1000000 at least
INFO: 2022-02-01 18:01:54,053 - TRANSFER_FROM_FAILED         --> Token is not approved for trade. LimitSwap will check approval right now.
INFO: 2022-02-01 18:01:54,054 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
INFO: 2022-02-01 18:01:54,054 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
INFO: 2022-02-01 18:01:54,054 - TRANSFER_FAILED              --> There is a whitelist
INFO: 2022-02-01 18:01:54,055 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds on your wallet to cover fees
INFO: 2022-02-01 18:01:54,056 - ... or your node is not working well
INFO: 2022-02-01 18:01:54,056 -------------------------------
ERROR: 2022-02-01 18:01:54,202 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-02-01 18:01:54,331 Your wallet already owns :  222222222.0 BFYC
INFO: 2022-02-01 18:01:54,333 You have reached MAXTOKENS for token  BFYC --> bot stops to buy
INFO: 2022-02-01 18:01:54,526 Current Wallet Balance is : 4.605116716416662407 BNB 
INFO: 2022-02-01 18:01:54,948 Sell Signal Found @0.000000018179994260
INFO: 2022-02-01 18:01:54,950 
INFO: 2022-02-01 18:01:54,950 Sell price in BFYC/BNB  : 0.000000018179994260
INFO: 2022-02-01 18:01:55,039 Current Wallet Balance is:  222222222.0 BFYC
INFO: 2022-02-01 18:01:55,239 sell condition 3
INFO: 2022-02-01 18:01:55,721 Transaction Hash =  *censored*
INFO: 2022-02-01 18:02:03,433 --------------------------------
INFO: 2022-02-01 18:02:03,434    SELL TRANSACTION FAILURE !
INFO: 2022-02-01 18:02:03,441 --------------------------------
INFO: 2022-02-01 18:02:03,441 Type of failures and possible causes:
INFO: 2022-02-01 18:02:03,451 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 1000000 at least
INFO: 2022-02-01 18:02:03,454 - TRANSFER_FROM_FAILED         --> Token is not approved for trade. LimitSwap will check approval right now.
INFO: 2022-02-01 18:02:03,460 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
INFO: 2022-02-01 18:02:03,461 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
INFO: 2022-02-01 18:02:03,461 - TRANSFER_FAILED              --> There is a whitelist
INFO: 2022-02-01 18:02:03,462 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds on your wallet to cover fees
INFO: 2022-02-01 18:02:03,463 - ... or your node is not working well
INFO: 2022-02-01 18:02:03,466 -------------------------------
ERROR: 2022-02-01 18:02:03,644 name 'cooldown' is not defined
Traceback (most recent call last):
  File "LimitSwap.py", line 5258, in <module>
  File "LimitSwap.py", line 2231, in auth
UnboundLocalError: local variable 'decode' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5203, in run
NameError: name 'cooldown' is not defined
INFO: 2022-02-01 18:02:03,789 Your wallet already owns :  222222222.0 BFYC
INFO: 2022-02-01 18:02:03,799 You have reached MAXTOKENS for token  BFYC --> bot stops to buy
INFO: 2022-02-01 18:02:04,047 Current Wallet Balance is : 4.505116816416662407 BNB 
INFO: 2022-02-01 18:02:04,457 Sell Signal Found @0.000000018105612880
INFO: 2022-02-01 18:02:04,467 
INFO: 2022-02-01 18:02:04,468 Sell price in BFYC/BNB  : 0.000000018105612880
INFO: 2022-02-01 18:02:04,675 Current Wallet Balance is:  222222222.0 BFYC
INFO: 2022-02-01 18:02:04,968 sell condition 3

tokens set up:

[
  {
    "ENABLED": "true",

    "SYMBOL": "BFYC",
    "ADDRESS": "0xa627Eb25dA4bCF6620DfF3f3fa87e4117eC71c6D",
    "KIND_OF_SWAP": "base", // enter "base" to use BUYAMOUNTINBASE , and "tokens" to use BUYAMOUNTINTOKENS
    "BUYAMOUNTINBASE": "0",
    "BUYAMOUNTINTOKEN": "",
    "MAX_BASE_AMOUNT_PER_EXACT_TOKENS_TRANSACTION": "0", // used with KIND_OF_SWAP = tokens

    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "0", // You can now put amount in % in this field
    "STOPLOSSPRICEINBASE": "0", // You can now put amount in % in this field
    "SLIPPAGE": "49",

    "MOONBAG": "0", // Bot will keep this amount in your wallet after SELL order
    "MAXTOKENS": "1", // Bot will stop if your balance > MAXTOKENS
    "MAX_SUCCESS_TRANSACTIONS_IN_A_ROW": "3",
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "3",

    "RUGDOC_CHECK": "false",
    "BUYAFTER_XXX_SECONDS": "0", // if you want the bot to wait XXX seconds before if makes the BUY Tx
    "WAIT_FOR_OPEN_TRADE": "false", // check Wiki, this is very useful
    "MULTIPLEBUYS": "false", // use this if you want bot to make multiple buys at the same time
    "BUYCOUNT": "2",
    "ALWAYS_CHECK_BALANCE": "false", // use this if you want bot to check your token balance between each price check

    "MINIMUM_LIQUIDITY_IN_DOLLARS": "10000",
    "WATCH_STABLES_PAIRS": "false", // use this if you want bot to check all Stable Liquidity pairs

    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "",
    "BASEADDRESS": "",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "true",
    "GAS": "300", // Team recommend you to use BOOST here
    "MAX_GAS": "99999", // Put here the maximum of GAS you want to pay if you use BOOST. If GAS > MAX_GAS Tx won't be made
    "BOOSTPERCENT": "30",
    "GASLIMIT": "333333", // Team recommend you to use 1000000 here
    "GASPRIORITY_FOR_ETH_ONLY": "1.5"
  }
]

Since I inserted quite a high gas, I spent 0.1 bnb on every failed transactions, and ended up losing 0.6 in total.

I have the feeling that "MAX_FAILED_TRANSACTIONS_IN_A_ROW" relates only to buy transactions, not sell. But that's just a guess.

In general, I have the feeling that the bot is optimized for buying and not so much for selling. Since the bot can be used for either, or both, I have some suggestions to make changes in the settings. I will make a detailed feature request about this shortly.

**Comment by tsarbuig** [comment]
you know why it does not work ? because you modified the bot code, you dumbass
