### ISSUE TITLE
Custom wss crashes and custom HTTPS issues

### ISSUE THREAD

**Issue by johnl1824** [tsarbuig/LimitSwap#4]
With the newest version v4.0, the bot automatically crashes when I try to load up a custom wss node. There log does not give any details about the crash, it just writes ***********************************. 
I also used the HTTPS version of the custom nodes and the speeds are slower than usual. currently getting maximum 2 checks/second.

**Comment by tsarbuig** [comment]
no problem on v4.0.2, wss: works well

check that : https://t.me/LimitSwap/98807
