### ISSUE TITLE
Error when liquidity already added - FTM blockchain

### ISSUE THREAD

**Issue by Sammex5** [tsarbuig/LimitSwap#40]
Hi! I try to snipe a launch on FTM and even with the "WAIT_FOR_OPEN_TRADE": "true_after_buy_tx_failed_no_message", i have an error and the bot shutdown. Here is one of the tx id : https://ftmscan.com/tx/0x657c53bc944c80e575d4e511aeb5788aac2c824c68f3ba460f04b5e95fce2ec8

The error in the log is : 

```
INFO: 2022-02-02 11:41:28,561 Buy Signal Found =-= Buy Signal Found =-= Buy Signal Found 
INFO: 2022-02-02 11:41:28,561 
INFO: 2022-02-02 11:41:28,561 Buy price in FCC/FTM : 0.000006920415224913
INFO: 2022-02-02 11:41:28,561 -----------------------------------------------------------
INFO: 2022-02-02 11:41:28,843 make_the_buy condition 4
INFO: 2022-02-02 11:41:29,573 Transaction Hash =  0x657c53bc944c80e575d4e511aeb5788aac2c824c68f3ba460f04b5e95fce2ec8
INFO: 2022-02-02 11:41:33,011 -------------------------------
INFO: 2022-02-02 11:41:33,011    BUY TRANSACTION FAILURE !
INFO: 2022-02-02 11:41:33,011 -------------------------------
INFO: 2022-02-02 11:41:33,011 Type of failures and possible causes:
INFO: 2022-02-02 11:41:33,012 - TRANSFER_FROM_FAILED         --> GASLIMIT too low. Raise it to GASLIMIT = 1000000 at least
INFO: 2022-02-02 11:41:33,012 - TRANSFER_FROM_FAILED         --> Your BASE token is not approved for trade
INFO: 2022-02-02 11:41:33,012 - INSUFFICIENT_OUTPUT_AMOUNT   --> SLIPPAGE too low
INFO: 2022-02-02 11:41:33,013 - TRANSFER_FAILED              --> Trading is not enabled. Use WAIT_FOR_OPEN_TRADE parameter after reading wiki
INFO: 2022-02-02 11:41:33,013 - TRANSFER_FAILED              --> There is a whitelist
INFO: 2022-02-02 11:41:33,013 - Sorry, We are unable to locate this TxnHash --> You don't have enough funds on your wallet to cover fees
INFO: 2022-02-02 11:41:33,013 - ... or your node is not working well
INFO: 2022-02-02 11:41:33,014 -------------------------------
ERROR: 2022-02-02 11:41:33,014 macosx:// is disabled on this system.
INFO: 2022-02-02 11:41:33,015 Notifying 1 service(s) asynchronously.
INFO: 2022-02-02 11:41:45,034 Sent Windows notification.
INFO: 2022-02-02 11:41:45,425 -----------------------------------------------------------------------------------------------------------------------------
INFO: 2022-02-02 11:41:45,426 WAIT_FOR_OPEN_TRADE is enabled
INFO: 2022-02-02 11:41:45,426 
ERROR: 2022-02-02 11:41:45,692 {'code': -32004, 'message': 'the method eth_newFilter does not exist/is not available'}
Traceback (most recent call last):
  File "C:\Users\Desktop\Desktop\LimitSwap-4.2.1.4\LimitSwap.py", line 5131, in run
    wait_for_open_trade(token, token['_IN_TOKEN'], token['_OUT_TOKEN'])
  File "C:\Users\Desktop\Desktop\LimitSwap-4.2.1.4\LimitSwap.py", line 2594, in wait_for_open_trade
    tx_filter = client.eth.filter({"filter_params": "pending", "address": inToken})
  File "C:\Users\Desktop\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\Desktop\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "C:\Users\Desktop\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32004, 'message': 'the method eth_newFilter does not exist/is not available'}
INFO: 2022-02-02 11:41:45,693 ERROR. Please go to /log folder and open your logs: you will find more details.
```

**Comment by Sammex5** [comment]
Here is the token.json

`[
  {
    "ENABLED": "true",

    "SYMBOL": "FCC",
    "ADDRESS": "0x3f21782d931583607F6e78f053E735513fF7d799",
    "KIND_OF_SWAP": "base", // enter "base" to use BUYAMOUNTINBASE , and "tokens" to use BUYAMOUNTINTOKENS
    "BUYAMOUNTINBASE": "50",
	
	
    "BUYAMOUNTINTOKEN": "(not used)",
    "MAX_BASE_AMOUNT_PER_EXACT_TOKENS_TRANSACTION": "(not used)", // used with KIND_OF_SWAP = tokens

    "BUYPRICEINBASE":  "999999",
    "SELLPRICEINBASE": "700%", // You can now put amount in % in this field
    "STOPLOSSPRICEINBASE": "60%", // You can now put amount in % in this field
    "SLIPPAGE": "49",

    "MOONBAG": "0", // Bot will keep this amount in your wallet after SELL order
    "MAXTOKENS": "0.1", // Bot will stop if your balance > MAXTOKENS
    "MAX_SUCCESS_TRANSACTIONS_IN_A_ROW": "4",
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "4",

    "RUGDOC_CHECK": "false",
    "BUYAFTER_XXX_SECONDS": "0", // if you want the bot to wait XXX seconds before if makes the BUY Tx
    "WAIT_FOR_OPEN_TRADE": "true_after_buy_tx_failed_no_message", // check Wiki, this is very useful
    "MULTIPLEBUYS": "false", // use this if you want bot to make multiple buys at the same time
    "BUYCOUNT": "2",
    "ALWAYS_CHECK_BALANCE": "false", // use this if you want bot to check your token balance between each price check

    "MINIMUM_LIQUIDITY_IN_DOLLARS": "100",
    "WATCH_STABLES_PAIRS": "false", // use this if you want bot to check all Stable Liquidity pairs

    "LIQUIDITYINNATIVETOKEN": "true",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "false",
    "GAS": "BOOST", // Team recommend you to use BOOST here
    "MAX_GAS": "9999", // Put here the maximum of GAS you want to pay if you use BOOST. If GAS > MAX_GAS Tx won't be made
    "BOOSTPERCENT": "30",
    "GASLIMIT": "1000000", // Team recommend you to use 1000000 here
    "GASPRIORITY_FOR_ETH_ONLY": "1.5"
  }
]
`

**Comment by tsarbuig** [comment]
hey bro, I understood what happened : scanning mempool is not allowed on some Public Nodes, they block you

on BSC public node, it seems to be open, but not on FTM default node --> you need to upgrade to a Private node


Still, I improved the way error is handled : it does not stop the bot anymore

So, if you use "true" option, let it run and it will continue to analyse the price with the "classic way" and buy when price has moved 

(of course, it's slower)
