### ISSUE TITLE
1inch Dex for LimitSwap users

### ISSUE THREAD

**Issue by yoloBcool** [tsarbuig/LimitSwap#42]
Please bring back 1inch Dex for Matic network enthusiasts.  Sure, 1inch is an aggregator but that actually ensures that the users get the best quotes for their swaps.
QuickSwap is currently charging a 0.3% Liquid Provide fee (or 0.6% for a round trip) per transaction on top of the gas fees.
Thank you!

**Comment by tsarbuig** [comment]
1inch API is not free anymore --> I cannot do it
