### ISSUE TITLE
Buy after a wallet sell

### ISSUE THREAD

**Issue by rulezzpt** [tsarbuig/LimitSwap#43]
Good afternoon Tsar,

I would like to know if it is possible or if it will be possible to do the following, bot to do something as simple as.  

Waiting for a sell order from a specific wallet and as soon it sells I proceed to buy that same coin.

e.g

1- Listing Wallet 0x........
2- When wallet 0x....... sells a specific currency, I buy the same currency
3- Then when reach 1/2% (or something) of the purchase price, sell automatically

4- Profit 👍  or n0t 👎 

I know it's a very, very high risky method but it doesn't hurt to try.

It would be to test on BSC and Polygon.

Thank you in advance for the way you have taken LimitSwap to another level, for your sympathy and always available to help the community.

Thanks.

**Comment by tsarbuig** [comment]
hi bro, it could be possible, but it's a completely different way to work, compared to existing code

I would have to re-write a big part of the bot...

Many people have already asked me if it's possible to track a wallet and make the same purchase / sell than him =
- when he buys : you buy
- when he sells : you sell

I'll let you know when I have time to implement it :)

**Comment by rulezzpt** [comment]
Good evening Tsar,

Yes, it may seem strange but I and other colleagues have analyzed several wallets in which they make a massive dump of crypto in order to create a panic sell and after some time they buy the coins in order to stabilize the price again.

Thanks mate.

**Comment by rulezzpt** [comment]
I managed to do what I wanted, in advance my thanks for your time, friendship and help you gave me.

Thanks.
