### ISSUE TITLE
Change values in Buy the dip mode

### ISSUE THREAD

**Issue by ghost** [tsarbuig/LimitSwap#51]
Change the price monitor to use the ATH price not the listing price. Also add the ability to change the default 50% dip price for a custom one like 35%-40% in tokens.json.

Add the ability to change the default buy value 20% above all time low for a custom one like 15%-17% in tokens.json.

**Comment by tsarbuig** [comment]
hey bro, to be honest with you I don't want to add too many parameters to the tokens.json, I'm afraid users will be lost if I had those new parameters 
But I've changed code to make it easier for you to change manually the values : 
- open LimitSwap.py
- look for "buy_the_dip_mode"
- change the "x0.5" and "x1.2" numbers here and it will do what you want :)

Example : if you want 15% above ATL , replace 1.2 by 1.15

Tell me if it's ok for you


![image](https://user-images.githubusercontent.com/70858574/159679803-594cf68c-2c9e-45a1-87ba-f1884b4f53dc.png)
