### ISSUE TITLE
Add Bot Loop option

### ISSUE THREAD

**Issue by ghost** [tsarbuig/LimitSwap#52]
If the bot has success (profit) with "buy the dip mode" + "trailing stop loss" we want to repeat this so please: 

-add an loop option in tokens.json example (loop:no or loop:yes)

-add loop time frame in hours example (looptime:48 or looptime=infinite) 

-the "buy the dip mode" + "trailing stop loss" parameters will be the same

It's repeating like the pingpong mode. This will be useful for the volatility of token launches the first few days.

**Comment by tsarbuig** [comment]
done :)
