### ISSUE TITLE
Trailing Stop Loss updated functionality

### ISSUE THREAD

**Issue by sufulouie** [tsarbuig/LimitSwap#54]
I had a couple of instances where the trailing stop loss feature worked against me.  Both times, I had a sell price set around 200-300% of buy price.  As the bot runs, it calculated a trailing stop loss based on ATH (that it sees while the bot runs).  But this ATH is no where near the sell price level I had set.  As the price drops lower, I do not want to sell, but it reached the calculated trailing stop loss level that it had calculated based on the ATH that the bot saw.  And the bot sells at a much lower level that I had wanted.  Taking significant losses both times. 
What I would like is for the trailing stop loss feature to not even activate until the sell price level is reached.  That way, the bot never sells for loss and keeps active until the price reaches the sell point.  Then the trailing stop loss is triggered and the bot monitors the price updates the ATH at that point only  That way the ATH is always at or greater than the sell price.  And the trailing stop loss feature will track the price increase and update the ATH from that point on, and sell only if the price falls to the level that was set (% of ATH).
This will make this feature much more useable for people who want to wait for a token to spike and keep while it is still low.

**Comment by tsarbuig** [comment]
done
