### ISSUE TITLE
multiple settings.json entries to trade on multiple networks

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/LimitSwap#55]
Use case: I have 2 trades on 2 networks happening around the same time.
One solution is correlating a settings.json entry with a tokens entry *or* moving all the settings in the tokens (which would create a big bloated file).

**Comment by tsarbuig** [comment]
the best and only way is to copy/paste the entire bot folder, and to run 2 instances of the bot bro

1 instance per blockchain
