### ISSUE TITLE
preapprove tries to do approval for each pair (but the approval is only needed with the router, not with the pair)

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/LimitSwap#57]

**Comment by tsarbuig** [comment]
I'm not sure what you mean here ? 

It will try to approve your base pair, so if you use WATCH STABLES PAIRS, it will approve BUSD / USDT / USDC / etc.

Just like on Pancake, when you need to approve every token, no ?

Am I wrong ?

**Comment by vaidab** [comment]
You approve in the token contract by writing to it the pancake swap router address. It doesn't have anything to do with any stable pair.
Basically you give the router the right to manage that specific token for you (and the router will convert your token to your stable). 
So it only needs 1 approve.

**Comment by vaidab** [comment]
Approval Tx for TOKEN will be created with gas = ...
^^^ only 1 of these needs to happen
