### ISSUE TITLE
MemoryError -> unclear error

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/LimitSwap#6]
Traceback (most recent call last):
  File "sniper.py", line 954, in <module>
    run()
  File "sniper.py", line 945, in run
    scan(tokens)
  File "sniper.py", line 677, in scan
    buy(pending, token, nonce, token['BUYAFTER_XXX_SECONDS'])
  File "sniper.py", line 759, in buy
    amount = token['BUYAMOUNT'] * DECIMALS
MemoryError

From tokens.json:

[
  {
    "SYMBOL": "XXX",
    "ADDRESS": "0x...",

    "USECUSTOMBASEPAIR": "True",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    
    "BUYAFTER_XXX_SECONDS": "3",

    "BUYAMOUNT": "0.0062",
    "MULTIPLEBUYS": "false",
    "BUYCOUNT": "5",
    "RUGCHECK": "false"
  }
]

I was using BUSD as a pair and I didn't have any BUSD. Also my BUYAMOUNT was too low for BUSD.
The error should be more descriptive.

**Comment by tsarbuig** [comment]
Thanks, i will check that asap

**Comment by tsarbuig** [comment]
solved on last Sniper version
