### ISSUE TITLE
web3.exceptions.InvalidAddress

### ISSUE THREAD

**Issue by bsatish417** [tsarbuig/LimitSwap#60]
web3.exceptions.InvalidAddress: ('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).'

Seems like wallet address needs to be wrapped with Web3.toChecksumAddress() function , there are lot of places where it is not done, so is this some thing that can be taken care ?

**Comment by tsarbuig** [comment]
should be fixed in last version
