### ISSUE TITLE
Bot buy but the the sell price was still 99999

### ISSUE THREAD

**Issue by Thrilseekah** [tsarbuig/LimitSwap#69]
Hello Tsar,

i have a problem again, now the bot is buying but not selling.

Sellprice is always 99999 no matter what I change in the tokens.json. 

Please help.

This is my tokens.json:

[
  {
    "ENABLED": "true",
	"SELECT_MODE": "limitswap", // available values : limitswap / buy_the_dip / trailing_stop / limitswap+trailing_stop / ping_pong / limitswap+ping_pong / snipe_on_pinksale / pinksale
    "SYMBOL": "MTVP",
    "ADDRESS": "0x64d2906391a82721bb24925fc16a3eff20c8756e",

// -----------  BUY / SELL  PARAMETERS ---------------------------------------------------------------------------------
    "KIND_OF_SWAP": "base",            // enter "base" to use BUYAMOUNTINBASE , and "tokens" to use BUYAMOUNTINTOKENS
    "BUYAMOUNTINBASE": "1",
    "BUYAMOUNTINTOKEN": "(not used)",
    "MAX_BASE_AMOUNT_PER_EXACT_TOKENS_TRANSACTION": "(not used)",     // used with KIND_OF_SWAP = tokens
    
    "BUYPRICEINBASE":  "0.0244",
    "SELLPRICEINBASE": "107%",         // You can now put amount in % in this field
    "SELLAMOUNTINTOKENS": "ALL",
    "STOPLOSSPRICEINBASE": "70%",      // You can now put amount in % in this field
    "SLIPPAGE": "49",

// -----------  BUY_THE_DIP / TRAILING_STOP_LOSS  PARAMETERS -----------------------------------------------------------
    "BUY_THE_DIP_PARAMETERS": "20%---10%",       // % of the dip under ATH, then % of the rise above ATL
    "TRAILING_STOP_LOSS_PARAMETER": "55%",       // put amount in % in this field. Enter '0' if you don't want to use it

// -----------  LIQUIDITY PARAMETERS -----------------------------------------------------------------------------------
    "WATCH_STABLES_PAIRS": "false",     // use this if you want bot to check all Stable Liquidity pairs
    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "MINIMUM_LIQUIDITY_IN_DOLLARS": "10000",

// -----------  COUNTER  ANTI BOT PARAMETERS --------------------------------------------------------------------------- 
    "WAIT_FOR_OPEN_TRADE": "true_after_buy_tx_failed", // check Wiki, this is very useful
    "CHECK_IF_TRADING_IS_ENABLED": "false",   // EXPERIMENTAL - BSC/AVAX/FTM only - put 'true' if you want the bot to check if openTrading is enabled after detecting liquidity
    "BUY_AND_SELL_TAXES_CHECK": "false",      // BSC/AVAX/FTM only - put 'true' if you want the bot to check BUY/SELL tax fees
    "MAX_BUY_TAX_IN_%": "20",                 // bot will buy as soon as BUY tax is lower that this value
    "MAX_SELL_TAX_IN_%": "20",                // bot will buy as soon as SELL tax is lower that this value
    "BUYAFTER_XXX_SECONDS": "0",
    "MULTIPLEBUYS": "false",            // you can use 2 options : 'several_wallets' or 'same_wallet'. Check wiki
    "BUYCOUNT": "2",

// -----------  GAS PARAMETERS -----------------------------------------------------------------------------------------
    "GAS": "BOOST",                     // Team recommend you to use BOOST here
    "GAS_FOR_APPROVE": "BOOST",         // Gas for Approval Tx. Team recommend you to use BOOST here
    "MAX_GAS": "9999",                  // Put here the maximum of GAS you want to pay if you use BOOST. If GAS > MAX_GAS Tx won't be made
    "BOOSTPERCENT": "30",
    "BOOSTPERCENT_FOR_APPROVE": "30",
    "GASLIMIT": "1000000",
    "GASPRIORITY_FOR_ETH_ONLY": "1.5",

// -----------  OTHER PARAMETERS ---------------------------------------------------------------------------------------
    "MOONBAG": "0",                     // Bot will keep this amount in your wallet after SELL order
    "MAXTOKENS": "1",                   // Bot will stop if your balance > MAXTOKENS
    "HASFEES": "true",
    "MAX_SUCCESS_TRANSACTIONS_IN_A_ROW": "2",
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "2",
    "RUGDOC_CHECK": "true",

// -----------  PINKSALE SNIPING ---------------------------------------------------------------------------------------- 
    "PINKSALE_PRESALE_ADDRESS": "enter here the presale address if you're sniping a Pinksale listing",
    "PINKSALE_PRESALE_START_TIMESTAMP":  "1647477029"
  }
]

And here the log:

NFO: 2022-04-29 15:29:43,550 Your bot is running    v4.4.1.2
INFO: 2022-04-29 15:29:43,866 Last version available v4.4.3.0 PLEASE KEEP UPDATED
INFO: 2022-04-29 15:33:26,295 Your tokens.json contains:
INFO: 2022-04-29 15:33:26,295 ENABLED= true ADDRESS= 0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82 KIND_OF_SWAP= base MINIMUM_LIQUIDITY_IN_DOLLARS= 10000 BUYAMOUNTINBASE= 0.005 BUYAMOUNTINTOKEN= 5 MAX_BASE...= 0.5 BUYPRICEINBASE= 0.0 SELLPRICEINBASE= 99999 STOPLOSSPRICEINBASE= 0 SELLAMOUNTINTOKENS= ALL SLIPPAGE= 15 WATCH_STABLES_PAIRS= true LIQUIDITYINNATIVETOKEN= false USECUSTOMBASEPAIR= true BASEADDRESS= 0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d BUY_THE_DIP_PARAMETERS= 50%---20% TRAILING_STOP_LOSS_PARAMETER= 80% BUY_AND_SELL_TAXES_CHECK= false MAX_BUY_TAX_IN_%= 20 MAX_SELL_TAX_IN_%= 20 BUYAFTER_XXX_SECONDS= 0 MULTIPLEBUYS= false BUYCOUNT= 2 GAS= BOOST MOONBAG= 0 MAXTOKENS= 1 HASFEES= false MAX_SUCCESS_TRANSACTIONS_IN_A_ROW= 2 MAX_FAILED_TRANSACTIONS_IN_A_ROW= 2
INFO: 2022-04-29 15:33:26,311 
INFO: 2022-04-29 15:33:27,282 BNB  balance :  0.769192985417187557
INFO: 2022-04-29 15:33:27,366 buy/sell condition = customF_nativeT
INFO: 2022-04-29 15:33:53,549 USDT balance :  0.0
INFO: 2022-04-29 15:33:53,549 buy/sell condition = customT_nativeF
INFO: 2022-04-29 15:33:55,569 BUSD balance :  3060.507435951185
INFO: 2022-04-29 15:33:55,622 buy/sell condition = customT_nativeF
INFO: 2022-04-29 15:33:59,209 USDC balance :  0.0
INFO: 2022-04-29 15:33:59,231 buy/sell condition = customT_nativeF
INFO: 2022-04-29 15:48:45,168 Your bot is running    v4.4.1.2
INFO: 2022-04-29 15:48:45,586 Last version available v4.4.3.0 PLEASE KEEP UPDATED
INFO: 2022-04-29 15:48:52,739 Your tokens.json contains:
INFO: 2022-04-29 15:48:52,739 ENABLED= true ADDRESS= 0x64d2906391a82721BB24925fc16A3EfF20c8756e KIND_OF_SWAP= base MINIMUM_LIQUIDITY_IN_DOLLARS= 10000 BUYAMOUNTINBASE= 250.0 BUYAMOUNTINTOKEN= (not used) MAX_BASE...= (not used) BUYPRICEINBASE= 0.032 SELLPRICEINBASE= 400% STOPLOSSPRICEINBASE= 85% SELLAMOUNTINTOKENS= ALL SLIPPAGE= 49 WATCH_STABLES_PAIRS= false LIQUIDITYINNATIVETOKEN= false USECUSTOMBASEPAIR= true BASEADDRESS= 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56 BUY_THE_DIP_PARAMETERS= 20%---10% TRAILING_STOP_LOSS_PARAMETER= 85% BUY_AND_SELL_TAXES_CHECK= false MAX_BUY_TAX_IN_%= 20 MAX_SELL_TAX_IN_%= 20 BUYAFTER_XXX_SECONDS= 0 MULTIPLEBUYS= false BUYCOUNT= 2 GAS= BOOST MOONBAG= 0 MAXTOKENS= 1 HASFEES= true MAX_SUCCESS_TRANSACTIONS_IN_A_ROW= 2 MAX_FAILED_TRANSACTIONS_IN_A_ROW= 2
INFO: 2022-04-29 15:48:52,740 
INFO: 2022-04-29 15:48:54,197 BUSD balance :  3060.507435951185
INFO: 2022-04-29 15:48:54,208 buy/sell condition = customT_nativeF
INFO: 2022-04-29 15:52:53,335 Found 108976.4481 liquidity for MTVP/BUSD
INFO: 2022-04-29 15:52:53,977 -----------------------------------------------------------
INFO: 2022-04-29 15:52:53,986 Buy Signal Found =-= Buy Signal Found =-= Buy Signal Found 
INFO: 2022-04-29 15:52:53,988 
INFO: 2022-04-29 15:52:53,989 Buy price in MTVP/BUSD : 0.023687288691358083
INFO: 2022-04-29 15:52:53,990 -----------------------------------------------------------
INFO: 2022-04-29 15:52:54,007 - MINIMUM_LIQUIDITY_IN_DOLLARS= 10000 $
INFO: 2022-04-29 15:52:55,993 Tx Hash =  0x6cf1f0acaaedf094fc22d426c3588b75d88198ca39a965569b00b50c28145c2b
INFO: 2022-04-29 15:53:02,727 ----------------------------------
INFO: 2022-04-29 15:53:02,752 SUCCESS : your buy Tx is confirmed
INFO: 2022-04-29 15:53:06,301 BUSD balance :  2810.507435951185
INFO: 2022-04-29 15:53:06,523 MTVP balance :  10141.211861400123
INFO: 2022-04-29 15:53:06,537 
INFO: 2022-04-29 15:53:06,542 You bought 10141.211861400123 MTVP tokens
INFO: 2022-04-29 15:53:06,555 ----------------------------------
ERROR: 2022-04-29 15:53:06,560 macosx:// is disabled on this system.
ERROR: 2022-04-29 15:53:06,561 windows:// is disabled on this system.
INFO: 2022-04-29 15:53:07,484 Tx Hash =  0xc2868cabde9665211cc7330303218887263c48c2ab233a7c7883289adeed47c2
INFO: 2022-04-29 15:53:13,223   Token is now approved : LimitSwap can sell this token
INFO: 2022-04-29 15:53:13,249 You have reached MAXTOKENS for MTVP token --> disabling trade
INFO: 2022-04-29 15:53:13,253 -----------------------------------------------------------------------------------------------------------------------------
INFO: 2022-04-29 15:53:13,261 TRAILING_STOP_LOSS mode is enabled
INFO: 2022-04-29 15:53:13,267 
INFO: 2022-04-29 15:53:13,268 Bot will:
INFO: 2022-04-29 15:53:13,269 1/ Wait for the price to go above SELLPRICEINBASE
INFO: 2022-04-29 15:53:13,271 2/ Monitor ATH
INFO: 2022-04-29 15:53:13,273 3/ Wait for price to drop to ( 85% * ATH ) to sell
INFO: 2022-04-29 15:53:13,274 
INFO: 2022-04-29 15:53:13,274 --> it will make you sell 15 % under the ATH :)
INFO: 2022-04-29 15:53:13,276 ------------------------------------------------------------------------------------------------------------------------------
INFO: 2022-04-29 15:53:19,392 TRAILING STOP | Token price 0.0250918483 | ATH 0.0250922952 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:53:31,255 TRAILING STOP | Token price 0.0307040043 | ATH 0.0307043202 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:54:10,198 TRAILING STOP | Token price 0.0309947366 | ATH 0.0312971151 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:54:16,346 TRAILING STOP | Token price 0.0295804152 | ATH 0.0312971151 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:54:22,195 TRAILING STOP | Token price 0.0292992957 | ATH 0.0312971151 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:54:25,267 TRAILING STOP | Token price 0.0290147478 | ATH 0.0312971151 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:54:34,392 TRAILING STOP | Token price 0.0291123981 | ATH 0.0312971151 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:54:47,287 TRAILING STOP | Token price 0.0286024728 | ATH 0.0312971151 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:54:59,295 TRAILING STOP | Token price 0.0328434415 | ATH 0.0329580025 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:55:05,205 TRAILING STOP | Token price 0.0326801390 | ATH 0.0329580025 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:55:08,133 TRAILING STOP | Token price 0.0325486909 | ATH 0.0329580025 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:55:11,177 TRAILING STOP | Token price 0.0325130214 | ATH 0.0329580025 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:55:41,063 TRAILING STOP | Token price 0.0332696214 | ATH 0.0336656342 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:55:59,375 TRAILING STOP | Token price 0.0343577991 | ATH 0.0345782041 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:56:05,396 TRAILING STOP | Token price 0.0345782041 | ATH 0.0348403052 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:56:11,293 TRAILING STOP | Token price 0.0314749983 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:56:36,147 TRAILING STOP | Token price 0.0319392633 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:56:54,391 TRAILING STOP | Token price 0.0316341843 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:57:00,345 TRAILING STOP | Token price 0.0319392633 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:57:03,154 TRAILING STOP | Token price 0.0318226271 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:57:09,245 TRAILING STOP | Token price 0.0318142709 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:57:18,354 TRAILING STOP | Token price 0.0317921833 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:57:21,130 TRAILING STOP | Token price 0.0317341357 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:57:51,374 TRAILING STOP | Token price 0.0325273542 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:58:00,410 TRAILING STOP | Token price 0.0326326849 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:58:15,154 TRAILING STOP | Token price 0.0327007062 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:58:21,074 TRAILING STOP | Token price 0.0336085358 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:58:30,056 TRAILING STOP | Token price 0.0327007062 | ATH 0.0348403312 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:58:57,180 TRAILING STOP | Token price 0.0356510372 | ATH 0.0357992556 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:00,291 TRAILING STOP | Token price 0.0356244336 | ATH 0.0357992556 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:09,241 TRAILING STOP | Token price 0.0356244336 | ATH 0.0363947498 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:15,183 TRAILING STOP | Token price 0.0363947225 | ATH 0.0363947498 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:21,083 TRAILING STOP | Token price 0.0368469477 | ATH 0.0369526433 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:33,166 TRAILING STOP | Token price 0.0367919059 | ATH 0.0369526433 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:45,297 TRAILING STOP | Token price 0.0370684304 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:48,207 TRAILING STOP | Token price 0.0366599979 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 15:59:54,407 TRAILING STOP | Token price 0.0368512565 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:00,295 TRAILING STOP | Token price 0.0369153546 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:06,097 TRAILING STOP | Token price 0.0367709237 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:09,184 TRAILING STOP | Token price 0.0367280185 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:15,157 TRAILING STOP | Token price 0.0367280185 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:24,970 TRAILING STOP | Token price 0.0360968771 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:30,123 TRAILING STOP | Token price 0.0360695333 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:36,597 TRAILING STOP | Token price 0.0364078775 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:39,190 TRAILING STOP | Token price 0.0357110453 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:45,227 TRAILING STOP | Token price 0.0354520555 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:48,156 TRAILING STOP | Token price 0.0351600350 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:54,152 TRAILING STOP | Token price 0.0355508381 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:57,277 TRAILING STOP | Token price 0.0354520555 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:00:58,904 Your tokens.json contains:
INFO: 2022-04-29 16:00:58,905 ENABLED= true ADDRESS= 0x64d2906391a82721BB24925fc16A3EfF20c8756e KIND_OF_SWAP= base MINIMUM_LIQUIDITY_IN_DOLLARS= 10000 BUYAMOUNTINBASE= 250.0 BUYAMOUNTINTOKEN= (not used) MAX_BASE...= (not used) BUYPRICEINBASE= 0.032 SELLPRICEINBASE= 200% STOPLOSSPRICEINBASE= 85% SELLAMOUNTINTOKENS= ALL SLIPPAGE= 49 WATCH_STABLES_PAIRS= false LIQUIDITYINNATIVETOKEN= false USECUSTOMBASEPAIR= true BASEADDRESS= 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56 BUY_THE_DIP_PARAMETERS= 20%---10% TRAILING_STOP_LOSS_PARAMETER= 85% BUY_AND_SELL_TAXES_CHECK= false MAX_BUY_TAX_IN_%= 20 MAX_SELL_TAX_IN_%= 20 BUYAFTER_XXX_SECONDS= 0 MULTIPLEBUYS= false BUYCOUNT= 2 GAS= BOOST MOONBAG= 0 MAXTOKENS= 1 HASFEES= true MAX_SUCCESS_TRANSACTIONS_IN_A_ROW= 2 MAX_FAILED_TRANSACTIONS_IN_A_ROW= 2
INFO: 2022-04-29 16:00:58,905 
INFO: 2022-04-29 16:01:00,145 TRAILING STOP | Token price 0.0350172567 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:01:09,058 TRAILING STOP | Token price 0.0345803260 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:01:31,391 TRAILING STOP | Token price 0.0353629371 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:02:19,284 TRAILING STOP | Token price 0.0331569014 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:02:25,165 TRAILING STOP | Token price 0.0330572030 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:02:28,145 TRAILING STOP | Token price 0.0324613184 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:03:09,371 TRAILING STOP | Token price 0.0322231705 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:03:18,349 TRAILING STOP | Token price 0.0324732359 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:03:21,218 TRAILING STOP | Token price 0.0320476953 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:03:42,324 TRAILING STOP | Token price 0.0320476953 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:04:03,170 TRAILING STOP | Token price 0.0331811059 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:04:06,337 TRAILING STOP | Token price 0.0320476953 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:04:15,313 TRAILING STOP | Token price 0.0331337916 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:04:24,142 TRAILING STOP | Token price 0.0332211632 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:04:27,088 TRAILING STOP | Token price 0.0323596749 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000
INFO: 2022-04-29 16:04:30,347 TRAILING STOP | Token price 0.0320476953 | ATH 0.0370749234 | Target Price = SELLPRICEINBASE = 99999.0000000000

**Comment by tsarbuig** [comment]
this was old version, it's fixed in recent releases
