### ISSUE TITLE
snipe miners function

### ISSUE THREAD

**Issue by NLSniper69** [tsarbuig/LimitSwap#70]
Hey dev,

To buy miners you need to interact with the dapp interface on their website. Can you make an option that the bot has a functions to snipe those miners without using their dapp interface

most miners launching on BNB chain, but it would be great if you can make it multichain, example of a miner that launched yesterday: https://bnb.cropsfarmer.online/

**Comment by tsarbuig** [comment]
is this still pertinent ?
