### ISSUE TITLE
add planning mode

### ISSUE THREAD

**Issue by ghost** [tsarbuig/LimitSwap#71]
we would like to plan new launches in advance in the same bot session, thanks to the new multithread module 

some ideas how can be done using the already implemented features:

-planning.json is a simplified version of token.json but with multiple tokens only for snipe and sell with trailing stop loss or normal "SELLPRICEINBASE" 
-fixed parameters for all snipes,it will be launched with a separate json file i.e:  python LimitSwap.py -t planning.json
-if one token doesn't have contract address or date in unixtime will be ignored
-the excution will be prioritized by the timestamp, After one snipe is done could show a message like: "Waiting 15 UTC  to snipe Cake on Pancakeswap you can change your planning.json parameters meanwhile".
-the user will be use planning.json to input new launches so the bot rewrites the status parameter i.e: the user inputs data for a new launch tomorrow (contract, date), so the default parameter will be "waiting" , and when the time come and the trade is done the bot will rewrite the status to "done"
-the planning.json could look like this:

        //SNIPE A
        "STATUS": "waiting"      //waiting: bot is waiting the date to trade, done: bot has completed the trade, ignore: is missing contract or date
        "SYMBOL": "CAKE",
        "ADDRESS": "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82",
        "EXCHANGE": "pancakeswap",
        "START_BUY_AFTER_TIMESTAMP": "1650332678",
 
        
        //SNIPE B
       "STATUS": "waiting"      //waiting: bot is waiting the date to trade, done: bot has completed the trade, ignore: is missing contract or date
        "SYMBOL": "VELAS",
        "ADDRESS": "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82",
        "EXCHANGE": "WAGYUSWAP",
        "START_BUY_AFTER_TIMESTAMP": "2350332678",

        //SNIPE C
       "STATUS": "waiting"      //waiting: bot is waiting the date to trade, done: bot has completed the trade, ignore: is missing contract or date
        "SYMBOL": "SHIBA",
        "ADDRESS": "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82",
        "EXCHANGE": "UNISWAP",
        "START_BUY_AFTER_TIMESTAMP": "2460332678",

maybe there is a bettter way to implement to the user input new launches than rewriting planning.json, like a simple gui

**Comment by tsarbuig** [comment]
too difficult and specific , to be honest... I think I won't do it, I'm sorry
