### ISSUE TITLE
Multiple wallet buy not working for me 

### ISSUE THREAD

**Issue by johnnybychance** [tsarbuig/LimitSwap#75]
I'm trying to buy with 5 wallets, only 1 works.
[tx-2022-05-05.log](https://github.com/tsarbuig/LimitSwap/files/8638994/tx-2022-05-05.log)
 
telegram: tim (@swappens)

**Comment by tsarbuig** [comment]
hey bro, 
- I need your tokens.json
- in your settings.json, you have parametered 5 wallets ? With 5 private keys and all ?

**Comment by tsarbuig** [comment]
closing the issue since I did not get any more details
