### ISSUE TITLE
need claim function via LimitSwap bot from NOT encrypted data

### ISSUE THREAD

**Issue by nastrdmt** [tsarbuig/LimitSwap#76]
today I've seen nice bot with 15 wallets tx claim and sell in 1 block [18110457 block](https://bscscan.com/txs?a=0x19259de26a05eab102ea3d153938767e4f22d2f6&p=3)
just wow! 
after he sold all tokens from 15 wallets he transferred BNBs in 1 wallet and send it in FTX.  [wallet link](https://bscscan.com/txs?a=0x04d94fa8de459c5273dd0524166b9ae8d2cbc350&p=1) So I'm sure its 1 bot with 15+ wallets

could you add this kind of function, i can test it (if you need some testers)
today i used LimitSwap for selling token after claimed via hands. It was so slow. i claimed my tokens via vesting website and sell via limitSwap bot for 4 blocks. it was 11 blocks after that bot sold his tokens, I'm jealous Tsar! Lets do our bot even better!

**Comment by tsarbuig** [comment]
I'm sorry, I did not understand how this works
