### ISSUE TITLE
Trailing stop loss in decimal not working

### ISSUE THREAD

**Issue by Chinjoy** [tsarbuig/LimitSwap#77]
Hi,

I am not able to put trailing stop in decimal. can you fix that. getting following error when trying.

ERROR: 2022-06-28 14:58:48,662 invalid literal for int() with base 10: '4.5'

below is the token.json. line number "TRAILING_STOP_LOSS": "4.5%", 
[
  {
    "ENABLED": "true",
    "SELECT_MODE": "trailing_stop", // available values : limitswap / buy_the_dip / trailing_stop / limitswap+trailing_stop / ping_pong / limitswap+ping_pong / snipe_on_pinksale / pinksale / telegram / telegram+trailing_stop / telegram+ping-pong
    "SYMBOL": "BPAD",
    "ADDRESS": "0x29132062319aa375e764ef8ef756f2b28c77a9c9",

// -----------  BUY / SELL  PARAMETERS ---------------------------------------------------------------------------------
    "KIND_OF_SWAP": "base",            // enter "base" to use BUYAMOUNTINBASE , and "tokens" to use BUYAMOUNTINTOKENS
    "BUYAMOUNTINBASE": "0.005",
    "BUYAMOUNTINTOKEN": "5",
    "MAX_BASE_AMOUNT_PER_EXACT_TOKENS_TRANSACTION": "0.001",     // used with KIND_OF_SWAP = tokens
    
    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "0.000011",         // You can now put amount in % in this field
    "SELLAMOUNTINTOKENS": "ALL",
    "STOPLOSSPRICEINBASE": "99%",      // You can now put amount in % in this field
    "SLIPPAGE": "0.25",

// -----------  BUY_THE_DIP / TRAILING_STOP_LOSS  PARAMETERS -----------------------------------------------------------
    "BUY_THE_DIP_PARAMETERS": "70%---20%",       // Step 1 : bot monitor ATH and wait for the price to dip XX% under ATH. Step 2 : bot monitor ATL and buy when price rise XX% above ATL
    "TRAILING_STOP_LOSS": "4.5%",       // Step 1 : bot wait for SELLPRICE to be reached. Step 2 : bot monitor ATH and sell when price drops XX% under ATH

// -----------  LIQUIDITY PARAMETERS -----------------------------------------------------------------------------------
    "WATCH_STABLES_PAIRS": "false",     // use this if you want bot to check all Stable Liquidity pairs
    "LIQUIDITYINNATIVETOKEN": "true",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "MINIMUM_LIQUIDITY_IN_DOLLARS": "30000",

// -----------  COUNTER  ANTI BOT PARAMETERS --------------------------------------------------------------------------- 
    "WAIT_FOR_OPEN_TRADE": "true_after_buy_tx_failed", // check Wiki, this is very useful
    "CHECK_IF_TRADING_IS_ENABLED": "false",   // EXPERIMENTAL - BSC/AVAX/FTM only - put 'true' if you want the bot to check if openTrading is enabled after detecting liquidity
    "BUY_AND_SELL_TAXES_CHECK": "false",      // BSC/AVAX/FTM only - put 'true' if you want the bot to check BUY/SELL tax fees
    "MAX_BUY_TAX_IN_%": "20",                 // bot will buy as soon as BUY tax is lower that this value
    "MAX_SELL_TAX_IN_%": "20",                // bot will buy as soon as SELL tax is lower that this value
    "BUYAFTER_XXX_SECONDS": "0",
    "MULTIPLEBUYS": "false",            // you can use 2 options : 'several_wallets' or 'same_wallet'. Check wiki
    "BUYCOUNT": "2",
    "MULTIPLESELLS": "false",           // same as MULTIPLEBUYS : 'several_wallets' or 'same_wallet'
    "SELLCOUNT": "2",

// -----------  GAS PARAMETERS -----------------------------------------------------------------------------------------
    "GAS": "9",                     // Team recommend you to use BOOST here
    "GAS_FOR_APPROVE": "5.1",         // Gas for Approval Tx. Team recommend you to use BOOST here
    "MAX_GAS": "9999",                  // Put here the maximum of GAS you want to pay if you use BOOST. If GAS > MAX_GAS Tx won't be made
    "BOOSTPERCENT": "30",
    "BOOSTPERCENT_FOR_APPROVE": "30",
    "GASLIMIT": "1000000",
    "GASPRIORITY_FOR_ETH_ONLY": "1.5",

// -----------  OTHER PARAMETERS ---------------------------------------------------------------------------------------
    "MOONBAG": "0",                     // Bot will keep this amount in your wallet after SELL order
    "MAXTOKENS": "1",                   // Bot will stop if your balance > MAXTOKENS
    "HASFEES": "false",
    "MAX_SUCCESS_TRANSACTIONS_IN_A_ROW": "2",
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "2",
    "RUGDOC_CHECK": "false",

// -----------  PINKSALE SNIPING ---------------------------------------------------------------------------------------- 
    "PINKSALE_PRESALE_ADDRESS": "enter here the presale address if you're sniping a Pinksale listing",
    "PINKSALE_PRESALE_START_TIMESTAMP":  "1647477029"
  }
]

**Comment by tsarbuig** [comment]
fixed
