### ISSUE TITLE
Telegram tax bug (?)

### ISSUE THREAD

**Issue by Unnamed2921** [tsarbuig/LimitSwap#78]

**Comment by tsarbuig** [comment]
Seems like this token is a little bit strange, no information appears on PancakeSwap on their info page...
https://pancakeswap.finance/info/token/0x04fa9eb295266d9d4650edcb879da204887dc3da

And the honeypot checker we use does not recognize it : https://trading-tigers.com/honeypot

So, I cannot do anything here
