### ISSUE TITLE
Add FstSwap to supported Dexes

### ISSUE THREAD

**Issue by michsindlinger** [tsarbuig/LimitSwap#79]
That's a transaction I did via: https://fstswap.finance/#/swap

https://bscscan.com/tx/0xaf328e1c31f3d12e797481b95d754bd14053deca6984c9d2055cf0c2dfdd1db3

Thanks a lot

**Comment by tsarbuig** [comment]
https://t.me/LimitSwap/118811

waiting for their Factory address
