### ISSUE TITLE
Add hybrid mode with TRAILING_STOP_LOSS and STOP_LOSS at a fixed price / percentage value of buy price

### ISSUE THREAD

**Issue by michsindlinger** [tsarbuig/LimitSwap#81]
Prevent big losses in case SELLPRICEINBASE will not reached in TRAILING_STOP_LOSS mode by adding an additional STOP_LOSS price / percentage of buy price.

Example:
- buy price 1$
- TRAILING_STOP_LOSS: 110%
- STOP_LOSS: 95%

-> In case the price increases only by 5% and then it suddenly drops, the additional STOP_LOSS will prevent a big loss by selling at 95% of buy price

**Comment by tsarbuig** [comment]
DONE in v5.0.3.9c
