### ISSUE TITLE
"strict" version of rugdoc chain, to continue only if status is ok

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#85]
Is it possible to make a parameter for RugDoc (for example, call it Auto or Strict) so that when answering:
     "OK": (style.GREEN + 'RUGDOC API RESULT : OK \n'
it is automatic - Yes
with other answers - No
I used to fix it myself (4.3.1.4), something like this:
         if honeypot_code == "OK":
            token['_RUGDOC_DECISION'] = "y"
         else:
             token['_RUGDOC_DECISION'] = "n"

**Comment by tsarbuig** [comment]
DONE with RUGDOC_CHECK = 'auto'
