### ISSUE TITLE
floating point numbers (1 decimal place) in BUY_THE_DIP_PARAMETERS

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#86]
Need to change BUY_THE_DIP_PARAMETERS to work with floating point numbers (1 decimal place): "BUY_THE_DIP_PARAMETERS": "97.0%---01.5%"

In code:
    dip_parameter = float(token['BUY_THE_DIP_PARAMETERS'][:4])
    rise_parameter = float(token['BUY_THE_DIP_PARAMETERS'][-5:-1])

For more flexible trading

**Comment by tsarbuig** [comment]
thanks, will be implemented in next release
