### ISSUE TITLE
START_SELL_AFTER_TIMESTAMP and START_BUY_AFTER_TIMESTAMP to work with seconds

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#87]
Need to change START_SELL_AFTER_TIMESTAMP and START_BUY_AFTER_TIMESTAMP to work with seconds, in my opinion it's easier and simpler:

pause.seconds(int(settings['START_SELL_AFTER_TIMESTAMP']))
and
pause.seconds(int(settings['START_BUY_AFTER_TIMESTAMP ']))

**Comment by tsarbuig** [comment]
You have another parameter for that bro : BUYAFTER_XXX_SECONDS

**Comment by MelnikovVV** [comment]
Well, then it is logical to add an additional parameter SELLAFTER_XXX_SECONDS to the file tokens.json

BUYAFTER_XXX_SECONDS - anti-bot parameter, it is used when buying is delayed inside the buy function
But you need to delay the sale after the purchase by a certain number of seconds
That is, the START_SELL_AFTER_TIMESTAMP parameter is suitable, but it is very inconvenient to use, because i set the delay for the task: wait a certain number of minutes after the purchase (date and time of purchase are unknown)
You can add SELLAFTER_XXX_SECONDS to the Sell function, it will delay the sale after each purchase by a certain number of seconds

**Comment by tsarbuig** [comment]
so, if a SELL signal is found , you want the SELLAFTER_XXX_SECONDS parameter to delay the SELL swap ?

**Comment by MelnikovVV** [comment]
Hi
Yes

**Comment by tsarbuig** [comment]
done in v5.0.4.4
