### ISSUE TITLE
BUYAMOUNTINBASE percentage value with custom base pair

### ISSUE THREAD

**Issue by michsindlinger** [tsarbuig/LimitSwap#89]
If I use a custom base pair and set buy amount in base to a percentage value, it seems it’s considering my bnb amount instead of my busd.

Thanks mate!

**Comment by tsarbuig** [comment]
strange... it works well for me bro

for instance : 

08-05 23:31:23.916027 - BUYAMOUNT CALCULATION -----------------------------------
08-05 23:31:23.916065 You have put BUYAMOUNTINBASE = 1%
08-05 23:31:23.916093 Your balance = 1.66378633176263001 BNBt
08-05 23:31:23.916126 --> Buyamount = 1% * 1.66378633176263001 = 0.0166378633176263 BNBt

and with custom base pair : 

08-05 23:32:16.490135 - BUYAMOUNT CALCULATION -----------------------------------
08-05 23:32:16.490189 You have put BUYAMOUNTINBASE = 1%
08-05 23:32:16.490235 Your balance = 0.41130694775900617 BUSD
08-05 23:32:16.490287 --> Buyamount = 1% * 0.41130694775900617 = 0.004113069477590062 BUSD


Please give me more details (tokens.json, screenshot... to reproduce the problem)

Thanks bro

**Comment by tsarbuig** [comment]
(in the meantime, I close it)
