### ISSUE TITLE
Buy the dip error calculate ATL

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#90]
Hello
    "SELECT_MODE": "ping_pong"

08-03 11:49:07.254742 You have entered BUY_THE_DIP_PARAMETERS = 03%---01%
08-03 11:49:07.254742
08-03 11:49:07.254742 Bot will:
08-03 11:49:07.254742 1/ Wait for the price to dip 3 % under ATH (All-Time-High)
08-03 11:49:07.254742 2/ Monitor the All Time Low (ATL) price in real-time, waiting for the dip to end
08-03 11:49:07.254742 3/ BUY when price has risen 1 % above ATL
08-03 11:49:07.254742
08-03 11:49:07.254742 --> it will make you buy  1 % above the dip :)

Token grew:

08-03 11:49:07.410990 BUY THE DIP  | Token price 2059.5776100692 | ATH 2059.5776100692 | WAIT for price < ATH-3% = 1997.7902817672
08-03 11:49:21.256233 BUY THE DIP  | Token price 2059.1778671934 | ATH 2059.5776100692 | WAIT for price < ATH-3% = 1997.7902817672
08-03 11:49:26.485160 BUY THE DIP  | Token price 2059.5075273536 | ATH 2059.5776100692 | WAIT for price < ATH-3% = 1997.7902817672
08-03 11:51:11.686061 BUY THE DIP  | Token price 2061.0063147791 | ATH 2061.0063147791 | WAIT for price < ATH-3% = 1999.1761253358
08-03 11:52:18.070135 BUY THE DIP  | Token price 2068.5084198257 | ATH 2068.5084198257 | WAIT for price < ATH-3% = 2006.4531672309
08-03 11:53:39.441088 BUY THE DIP  | Token price 2076.0241266392 | ATH 2076.0241266392 | WAIT for price < ATH-3% = 2013.7434028400
08-03 11:53:50.540778 BUY THE DIP  | Token price 2076.1154427619 | ATH 2076.1154427619 | WAIT for price < ATH-3% = 2013.8319794790
08-03 11:54:03.559813 BUY THE DIP  | Token price 2077.6202479857 | ATH 2077.6202479857 | WAIT for price < ATH-3% = 2015.2916405461
08-03 11:54:14.578386 BUY THE DIP  | Token price 2081.2947628172 | ATH 2081.2947628172 | WAIT for price < ATH-3% = 2018.8559199327
08-03 11:54:51.004011 BUY THE DIP  | Token price 2082.8723515330 | ATH 2082.8723515330 | WAIT for price < ATH-3% = 2020.3861809870
08-03 11:55:07.215386 BUY THE DIP  | Token price 2083.6259067630 | ATH 2083.6259067630 | WAIT for price < ATH-3% = 2021.1171295601
08-03 11:55:29.325979 BUY THE DIP  | Token price 2100.2078529912 | ATH 2100.2078529912 | WAIT for price < ATH-3% = 2037.2016174014

came the condition READY TO BUY

08-03 12:40:48.224085 READY TO BUY | Token price 2231.9053173523 | ATL 2059.5776100692 | BUY when price > ATL+1% = 2080.1733861699

and immediately purchase by incorrect ATL calculation

08-03 12:40:48.224085 BUY THE DIP target reached : LET'S BUY @ 2231.905317352253405260853469

08-03 12:40:48.224085 - BUY SIGNAL FOUND -/!\-/!\-/!\-/!\-/!\--------------------
08-03 12:40:48.224085 Buy price in TTC/USDT : 2231.905317352253405261
08-03 12:40:48.224085 You hold 0.0 TTC before this BUY order

08-03 12:40:48.224085 - LIQUIDITY CHECK -----------------------------------------
08-03 12:40:48.224085 MINIMUM_LIQUIDITY_IN_DOLLARS= 10000 $
08-03 12:40:49.003836 Current TTC/USDT Liquidity = 2832068.405262 $
08-03 12:40:49.003836 --> Enough liquidity detected : let's go!

result - sale by stop loss

in last public version , i fixed it like this:

func buy_the_dip_mode

.....

            elif token['_QUOTE'] <= (token['_ALL_TIME_HIGH'] * (dip_parameter/100)):
                if token['_BUY_THE_DIP_ACTIVE'] == False:
                    token['_ALL_TIME_LOW'] = token['_QUOTE']

....

**Comment by tsarbuig** [comment]
thanks for this very good suggestion. Will be fixed with your solution in next release
