### ISSUE TITLE
"BUYAMOUNTINBASE" 100%

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#91]
Hello
It is better not to use 100% in the "BUYAMOUNTINBASE" value at all
In this case, there is a very high probability of an error during the purchase - Fail with error 'TransferHelper: TRANSFER_FROM_FAILED', because there are not enough funds due to a change in the price of the token (USECUSTOMBASEPAIR).
100% will never work

**Comment by tsarbuig** [comment]
you're right, I already had implemented a control for "BUYAMOUNTINBASE = all" but I forgot to add "BUYAMOUNTINBASE = 100%" 

--> will be fixed in next version
