### ISSUE TITLE
SELLPRICE CALCULATION ERROR

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#92]
Hello
08-04 08:14:35.280572 READY TO BUY | Token price 1553.1529913342 | ATL 1526.8874967702 | BUY when price > ATL+1% = 1542.1563717379

08-04 08:14:35.280572 BUY THE DIP target reached : LET'S BUY @ 1553.152991334210355489631183

08-04 08:14:35.280572 - BUY SIGNAL FOUND -/!\-/!\-/!\-/!\-/!\--------------------
08-04 08:14:35.280572 Buy price in TTC/USDT : 1553.152991334210355490
08-04 08:14:35.280572 You hold 0.0 TTC before this BUY order

08-04 08:14:35.280572 - LIQUIDITY CHECK -----------------------------------------
08-04 08:14:35.280572 MINIMUM_LIQUIDITY_IN_DOLLARS= 10000 $
08-04 08:14:36.061822 Current TTC/USDT Liquidity = 2406796.119712 $
08-04 08:14:36.061822 --> Enough liquidity detected : let's go!

08-04 08:14:36.655571 - TX HASH -------------------------------------------------
08-04 08:14:36.655571 0x627a021ec88a7d884af597988f84f6348754c9ada266ae00f8e87fd24b529dc3
08-04 08:14:36.655571 Checking for transaction confirmation (waiting 60 seconds).

08-04 08:14:40.066261 - SUCCESS : BUY CONFIRMED ---------------------------------
08-04 08:14:40.352356 USDT balance :  236.91565125199736
08-04 08:14:40.512941 TTC balance :  0.0
08-04 08:14:40.512941 You bought 0.0 TTC tokens

08-04 08:14:40.512941 - SELLPRICE CALCULATION ERROR -----------------------------
08-04 08:14:40.512941 TTC  cost per token was not properly calculated.
08-04 08:14:40.512941 --> We will set SELLPRICEINBASE = 99999 to avoid you selling this token with a wrong price.
08-04 08:14:40.512941 Please report this error to the dev.
08-04 08:14:40.512941 --> STOPLOSSPRICEINBASE =  95% * 0 =  0.0
08-04 08:14:40.512941

**Comment by MelnikovVV** [comment]
08-04 18:12:57.081136 READY TO BUY | Token price 1968.7529895187 | ATL 1957.5173713760 | BUY when price > ATL+1% = 1977.0925450897

08-04 18:13:02.826779 BUY THE DIP target reached : LET'S BUY @ 1977.327776730179039077484049


08-04 18:13:02.842400 - BUY SIGNAL FOUND -/!\-/!\-/!\-/!\-/!\--------------------
08-04 18:13:02.842400 Buy price in TTC/USDT : 1977.327776730179039077
08-04 18:13:02.842400 You hold 0.0 TTC before this BUY order

08-04 18:13:02.842400 - LIQUIDITY CHECK -----------------------------------------
08-04 18:13:02.842400 MINIMUM_LIQUIDITY_IN_DOLLARS= 10000 $
08-04 18:13:03.248649 Current TTC/USDT Liquidity = 2761143.778325 $
08-04 18:13:03.248649 --> Enough liquidity detected : let's go!


08-04 18:13:03.576779 - TX HASH -------------------------------------------------
08-04 18:13:03.576779 0xed895d822f9c04dba64e3b24996eaff35a0a316260cb7ac68d1e6649096515c5
08-04 18:13:03.576779 Checking for transaction confirmation (waiting 60 seconds).

08-04 18:13:07.438051 - SUCCESS : BUY CONFIRMED ---------------------------------
08-04 18:13:07.578677 USDT balance :  240.46486212306547
08-04 18:13:07.656803 TTC balance :  0.0
08-04 18:13:07.656803 You bought 0.0 TTC tokens


08-04 18:13:07.672424 - SELLPRICE CALCULATION ERROR -----------------------------
08-04 18:13:07.672424 TTC  cost per token was not properly calculated.
08-04 18:13:07.672424 --> We will set SELLPRICEINBASE = 99999 to avoid you selling this token with a wrong price.
08-04 18:13:07.672424 Please report this error to the dev.
08-04 18:13:07.672424 --> STOPLOSSPRICEINBASE =  98% * 0 =  0.0
08-04 18:13:07.672424

**Comment by tsarbuig** [comment]
this problem is very strange , I don't understand why it happens...

- I added more logs
- I added a 3 seconds wait time after BUY

We will see if it solves the problem in next version. I keep this issue opened

**Comment by MelnikovVV** [comment]
I suggest, in case of an error, to take the price from this line:
08-04 18:13:02.842400 Buy price in TTC/USDT : 1977.327776730179039077

it's not quite correct, but better than 0 :)
from this price can be calculated:
SELLPRICEINBASE
STOPLOSSPRICEINBASE

**Comment by tsarbuig** [comment]
that's actually a very good idea bro !! why did I did not think about that before lol
Implemented !
