### ISSUE TITLE
online update STOPLOSS

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#95]
Hello
When updating a file tokens.json:

08-08 13:12:51.553847 Loading tokens from ./tokens.json
08-08 13:12:51.647591 BNB  price: 329.03 $
08-08 13:12:51.647591 New TRAILING_STOP_LOSS: 1%
08-08 13:12:51.647591 New SELLPRICEINBASE: 1200
08-08 13:12:51.647591 New SLIPPAGE: 1

My suggestion is to online update parameter  STOPLOSS:

08-08 13:12:51.553847 Loading tokens from ./tokens.json
08-08 13:12:51.647591 BNB  price: 329.03 $
08-08 13:12:51.647591 New TRAILING_STOP_LOSS: 1%
08-08 13:12:51.647591 New SELLPRICEINBASE: 1200
08-08 13:12:51.647591 New SLIPPAGE: 1
**08-08 13:12:51.647591 New STOPLOSS: 1100**

**Comment by tsarbuig** [comment]
will be done in next version
