### ISSUE TITLE
BUY_THE_DIP_PARAMETERS

### ISSUE THREAD

**Issue by MelnikovVV** [tsarbuig/LimitSwap#96]
Hello
The upper limit of the parameter must be made as a range
I set: 03.0%---01.0%
Script in READY TO BUY mode
If the price rises not by 1 percent, but by 5 percent, then it is no longer profitable to buy (pump)
If a range were given:
03.0%---01.0%-02.0%
Then, the script would not buy at an inflated price

**Comment by tsarbuig** [comment]
that's a good idea bro, but to be honest I'm afraid it would be a little bit too complicated for users...

What do you think ? Are you sure it's really useful ?

**Comment by MelnikovVV** [comment]
I don't think very many people use this mod.
I'm trying to use it, but ...... you need to complicate to get the effect of BUY_THE_DIP
If the script has found THE_DIP and is waiting for an increase, but a pump occurs, you can’t buy, because it turns out that you bought at an unfavorable rate
Plus, the purchase occurs at an even higher price, since the price of the coin is increasing:
03.0%---01.0%
BUY THE DIP | Token price 0.18 | ATH 0.20 | WAIT for price < ATH-03.0% = 0.194
READY TO BUY | Token price 0.193 | ATL 0.193 | WAIT for price > ATL+01.0% = 0.19493
READY TO BUY | Token price 0.198 | ATL 0.193 | WAIT for price > ATL+01.0% = 0.19493
The purchase price is not very good anymore, as there was a pump, but while the script is buying, the real purchase price is even higher - 0.199
If there were a restriction on the second parameter, then the script would not buy a coin, but would wait for more interesting conditions for buying:
03.0%---01.0-01.5%
The script would buy only if the price did not exceed 0.195895 (0.193*1.015)
We can put it up for discussion in the telegram group

**Comment by tsarbuig** [comment]
ok bro, I will implement it :)

**Comment by tsarbuig** [comment]
done in v5.0.4.4

![image](https://user-images.githubusercontent.com/70858574/186278894-3346bd73-a07a-4b43-9435-5fd18bfb9730.png)
