### ISSUE TITLE
Telegram - Tokens without liquidity

### ISSUE THREAD

**Issue by wibuf** [tsarbuig/LimitSwap#99]
Would like to have the bot setup to watch telegram channels that source new tokens that haven't had liquidity added yet. A sample telegram would be: https://t.me/CMC_fastest_alerts

The bot would then watch these contracts and scan the mempool/buy in the same block liquidity is added like how the sniper bot works now. 

Would need the telegram portion to have a filter/whitelist for terms. Using the CMC_fastest_alerts as a sample, whitelisting the words "first pump" would only add new tokens that haven't had liquidity added yet. 

Let me know if you have any questions or need help testing, thanks

**Comment by tsarbuig** [comment]
done on 5.0.4.3
